<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN7P4A-0081" name="Default test" tests="1" failures="1" timestamp="5 Jul 2017 12:55:32 GMT" time="96.945" errors="0">
  <testcase name="testRunner" time="96.764" classname="testscripts.LoginScenario.TestForMarineValidLogin">
    <failure type="com.cognizant.framework.FrameworkException" message="Error while capturing the screenshot">
      <![CDATA[com.cognizant.framework.FrameworkException: Error while capturing the screenshot
	at com.cognizant.framework.selenium.SeleniumReport.takeScreenshot(SeleniumReport.java:93)
	at com.cognizant.framework.Report.handleStepInvolvingScreenshot(Report.java:285)
	at com.cognizant.framework.Report.updateTestLog(Report.java:226)
	at com.cognizant.Craft.DriverScript.exceptionHandler(DriverScript.java:698)
	at com.cognizant.Craft.DriverScript.executeCRAFTTestIterations(DriverScript.java:570)
	at com.cognizant.Craft.DriverScript.executeCraft(DriverScript.java:155)
	at com.cognizant.Craft.DriverScript.driveTestExecution(DriverScript.java:147)
	at testscripts.LoginScenario.TestForMarineValidLogin.testRunner(TestForMarineValidLogin.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testRunner -->
</testsuite> <!-- Default test -->
